# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3323dff4307837b6bb0c3dd943a1d86f60f16ad00bae0044538928ca626bdbc0dbeb488029dfa0999705127f021322a43cab4399944fe7d51b210443605d9883

test:
  secret_key_base: 7f4f1148eb0bf935ee7184700ca10dad556b16ce3e2f0bb99d5e27e26173a3350aad7958fb5f796051e32973eca35b4ea8012bb1aa59da08e4ac81b76b0a1bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
